//go:build ignore
// +build ignore

// generate with: GOARCH=arm go tool cgo -godefs ctypes.go | gofmt > types_arm.go

// Copyright 2018 Axel Wagner
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fb

/*
#define CONFIG_FB_BACKLIGHT
#include <linux/fb.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
*/
import "C"

type FixScreeninfo C.struct_fb_fix_screeninfo

type Bitfield C.struct_fb_bitfield

type VarScreeninfo C.struct_fb_var_screeninfo

type Cmap C.struct_fb_cmap

type Con2fbmap C.struct_fb_con2fbmap

type Vblank C.struct_fb_vblank

type Copyarea C.struct_fb_copyarea

type Fillrect C.struct_fb_fillrect

type Image C.struct_fb_image

type Curpos C.struct_fbcurpos

type Cursor C.struct_fb_cursor

const (
	FB_MAX                       = C.FB_MAX
	FBIOGET_VSCREENINFO          = C.FBIOGET_VSCREENINFO
	FBIOPUT_VSCREENINFO          = C.FBIOPUT_VSCREENINFO
	FBIOGET_FSCREENINFO          = C.FBIOGET_FSCREENINFO
	FBIOGETCMAP                  = C.FBIOGETCMAP
	FBIOPUTCMAP                  = C.FBIOPUTCMAP
	FBIOPAN_DISPLAY              = C.FBIOPAN_DISPLAY
	FBIO_CURSOR                  = C.FBIO_CURSOR
	FBIOGET_CON2FBMAP            = C.FBIOGET_CON2FBMAP
	FBIOPUT_CON2FBMAP            = C.FBIOPUT_CON2FBMAP
	FBIOBLANK                    = C.FBIOBLANK
	FBIOGET_VBLANK               = C.FBIOGET_VBLANK
	FBIO_ALLOC                   = C.FBIO_ALLOC
	FBIO_FREE                    = C.FBIO_FREE
	FBIOGET_GLYPH                = C.FBIOGET_GLYPH
	FBIOGET_HWCINFO              = C.FBIOGET_HWCINFO
	FBIOPUT_MODEINFO             = C.FBIOPUT_MODEINFO
	FBIOGET_DISPINFO             = C.FBIOGET_DISPINFO
	FBIO_WAITFORVSYNC            = C.FBIO_WAITFORVSYNC
	FB_TYPE_PACKED_PIXELS        = C.FB_TYPE_PACKED_PIXELS
	FB_TYPE_PLANES               = C.FB_TYPE_PLANES
	FB_TYPE_INTERLEAVED_PLANES   = C.FB_TYPE_INTERLEAVED_PLANES
	FB_TYPE_TEXT                 = C.FB_TYPE_TEXT
	FB_TYPE_VGA_PLANES           = C.FB_TYPE_VGA_PLANES
	FB_TYPE_FOURCC               = C.FB_TYPE_FOURCC
	FB_AUX_TEXT_MDA              = C.FB_AUX_TEXT_MDA
	FB_AUX_TEXT_CGA              = C.FB_AUX_TEXT_CGA
	FB_AUX_TEXT_S3_MMIO          = C.FB_AUX_TEXT_S3_MMIO
	FB_AUX_TEXT_MGA_STEP16       = C.FB_AUX_TEXT_MGA_STEP16
	FB_AUX_TEXT_MGA_STEP8        = C.FB_AUX_TEXT_MGA_STEP8
	FB_AUX_TEXT_SVGA_GROUP       = C.FB_AUX_TEXT_SVGA_GROUP
	FB_AUX_TEXT_SVGA_MASK        = C.FB_AUX_TEXT_SVGA_MASK
	FB_AUX_TEXT_SVGA_STEP2       = C.FB_AUX_TEXT_SVGA_STEP2
	FB_AUX_TEXT_SVGA_STEP4       = C.FB_AUX_TEXT_SVGA_STEP4
	FB_AUX_TEXT_SVGA_STEP8       = C.FB_AUX_TEXT_SVGA_STEP8
	FB_AUX_TEXT_SVGA_STEP16      = C.FB_AUX_TEXT_SVGA_STEP16
	FB_AUX_TEXT_SVGA_LAST        = C.FB_AUX_TEXT_SVGA_LAST
	FB_AUX_VGA_PLANES_VGA4       = C.FB_AUX_VGA_PLANES_VGA4
	FB_AUX_VGA_PLANES_CFB4       = C.FB_AUX_VGA_PLANES_CFB4
	FB_AUX_VGA_PLANES_CFB8       = C.FB_AUX_VGA_PLANES_CFB8
	FB_VISUAL_MONO01             = C.FB_VISUAL_MONO01
	FB_VISUAL_MONO10             = C.FB_VISUAL_MONO10
	FB_VISUAL_TRUECOLOR          = C.FB_VISUAL_TRUECOLOR
	FB_VISUAL_PSEUDOCOLOR        = C.FB_VISUAL_PSEUDOCOLOR
	FB_VISUAL_DIRECTCOLOR        = C.FB_VISUAL_DIRECTCOLOR
	FB_VISUAL_STATIC_PSEUDOCOLOR = C.FB_VISUAL_STATIC_PSEUDOCOLOR
	FB_VISUAL_FOURCC             = C.FB_VISUAL_FOURCC
	FB_ACCEL_NONE                = C.FB_ACCEL_NONE
	FB_ACCEL_ATARIBLITT          = C.FB_ACCEL_ATARIBLITT
	FB_ACCEL_AMIGABLITT          = C.FB_ACCEL_AMIGABLITT
	FB_ACCEL_S3_TRIO64           = C.FB_ACCEL_S3_TRIO64
	FB_ACCEL_NCR_77C32BLT        = C.FB_ACCEL_NCR_77C32BLT
	FB_ACCEL_S3_VIRGE            = C.FB_ACCEL_S3_VIRGE
	FB_ACCEL_ATI_MACH64GX        = C.FB_ACCEL_ATI_MACH64GX
	FB_ACCEL_DEC_TGA             = C.FB_ACCEL_DEC_TGA
	FB_ACCEL_ATI_MACH64CT        = C.FB_ACCEL_ATI_MACH64CT
	FB_ACCEL_ATI_MACH64VT        = C.FB_ACCEL_ATI_MACH64VT
	FB_ACCEL_ATI_MACH64GT        = C.FB_ACCEL_ATI_MACH64GT
	FB_ACCEL_SUN_CREATOR         = C.FB_ACCEL_SUN_CREATOR
	FB_ACCEL_SUN_CGSIX           = C.FB_ACCEL_SUN_CGSIX
	FB_ACCEL_SUN_LEO             = C.FB_ACCEL_SUN_LEO
	FB_ACCEL_IMS_TWINTURBO       = C.FB_ACCEL_IMS_TWINTURBO
	FB_ACCEL_3DLABS_PERMEDIA2    = C.FB_ACCEL_3DLABS_PERMEDIA2
	FB_ACCEL_MATROX_MGA2064W     = C.FB_ACCEL_MATROX_MGA2064W
	FB_ACCEL_MATROX_MGA1064SG    = C.FB_ACCEL_MATROX_MGA1064SG
	FB_ACCEL_MATROX_MGA2164W     = C.FB_ACCEL_MATROX_MGA2164W
	FB_ACCEL_MATROX_MGA2164W_AGP = C.FB_ACCEL_MATROX_MGA2164W_AGP
	FB_ACCEL_MATROX_MGAG100      = C.FB_ACCEL_MATROX_MGAG100
	FB_ACCEL_MATROX_MGAG200      = C.FB_ACCEL_MATROX_MGAG200
	FB_ACCEL_SUN_CG14            = C.FB_ACCEL_SUN_CG14
	FB_ACCEL_SUN_BWTWO           = C.FB_ACCEL_SUN_BWTWO
	FB_ACCEL_SUN_CGTHREE         = C.FB_ACCEL_SUN_CGTHREE
	FB_ACCEL_SUN_TCX             = C.FB_ACCEL_SUN_TCX
	FB_ACCEL_MATROX_MGAG400      = C.FB_ACCEL_MATROX_MGAG400
	FB_ACCEL_NV3                 = C.FB_ACCEL_NV3
	FB_ACCEL_NV4                 = C.FB_ACCEL_NV4
	FB_ACCEL_NV5                 = C.FB_ACCEL_NV5
	FB_ACCEL_CT_6555x            = C.FB_ACCEL_CT_6555x
	FB_ACCEL_3DFX_BANSHEE        = C.FB_ACCEL_3DFX_BANSHEE
	FB_ACCEL_ATI_RAGE128         = C.FB_ACCEL_ATI_RAGE128
	FB_ACCEL_IGS_CYBER2000       = C.FB_ACCEL_IGS_CYBER2000
	FB_ACCEL_IGS_CYBER2010       = C.FB_ACCEL_IGS_CYBER2010
	FB_ACCEL_IGS_CYBER5000       = C.FB_ACCEL_IGS_CYBER5000
	FB_ACCEL_SIS_GLAMOUR         = C.FB_ACCEL_SIS_GLAMOUR
	FB_ACCEL_3DLABS_PERMEDIA3    = C.FB_ACCEL_3DLABS_PERMEDIA3
	FB_ACCEL_ATI_RADEON          = C.FB_ACCEL_ATI_RADEON
	FB_ACCEL_I810                = C.FB_ACCEL_I810
	FB_ACCEL_SIS_GLAMOUR_2       = C.FB_ACCEL_SIS_GLAMOUR_2
	FB_ACCEL_SIS_XABRE           = C.FB_ACCEL_SIS_XABRE
	FB_ACCEL_I830                = C.FB_ACCEL_I830
	FB_ACCEL_NV_10               = C.FB_ACCEL_NV_10
	FB_ACCEL_NV_20               = C.FB_ACCEL_NV_20
	FB_ACCEL_NV_30               = C.FB_ACCEL_NV_30
	FB_ACCEL_NV_40               = C.FB_ACCEL_NV_40
	FB_ACCEL_XGI_VOLARI_V        = C.FB_ACCEL_XGI_VOLARI_V
	FB_ACCEL_XGI_VOLARI_Z        = C.FB_ACCEL_XGI_VOLARI_Z
	FB_ACCEL_OMAP1610            = C.FB_ACCEL_OMAP1610
	FB_ACCEL_TRIDENT_TGUI        = C.FB_ACCEL_TRIDENT_TGUI
	FB_ACCEL_TRIDENT_3DIMAGE     = C.FB_ACCEL_TRIDENT_3DIMAGE
	FB_ACCEL_TRIDENT_BLADE3D     = C.FB_ACCEL_TRIDENT_BLADE3D
	FB_ACCEL_TRIDENT_BLADEXP     = C.FB_ACCEL_TRIDENT_BLADEXP
	FB_ACCEL_CIRRUS_ALPINE       = C.FB_ACCEL_CIRRUS_ALPINE
	FB_ACCEL_NEOMAGIC_NM2070     = C.FB_ACCEL_NEOMAGIC_NM2070
	FB_ACCEL_NEOMAGIC_NM2090     = C.FB_ACCEL_NEOMAGIC_NM2090
	FB_ACCEL_NEOMAGIC_NM2093     = C.FB_ACCEL_NEOMAGIC_NM2093
	FB_ACCEL_NEOMAGIC_NM2097     = C.FB_ACCEL_NEOMAGIC_NM2097
	FB_ACCEL_NEOMAGIC_NM2160     = C.FB_ACCEL_NEOMAGIC_NM2160
	FB_ACCEL_NEOMAGIC_NM2200     = C.FB_ACCEL_NEOMAGIC_NM2200
	FB_ACCEL_NEOMAGIC_NM2230     = C.FB_ACCEL_NEOMAGIC_NM2230
	FB_ACCEL_NEOMAGIC_NM2360     = C.FB_ACCEL_NEOMAGIC_NM2360
	FB_ACCEL_NEOMAGIC_NM2380     = C.FB_ACCEL_NEOMAGIC_NM2380
	FB_ACCEL_PXA3XX              = C.FB_ACCEL_PXA3XX
	FB_ACCEL_SAVAGE4             = C.FB_ACCEL_SAVAGE4
	FB_ACCEL_SAVAGE3D            = C.FB_ACCEL_SAVAGE3D
	FB_ACCEL_SAVAGE3D_MV         = C.FB_ACCEL_SAVAGE3D_MV
	FB_ACCEL_SAVAGE2000          = C.FB_ACCEL_SAVAGE2000
	FB_ACCEL_SAVAGE_MX_MV        = C.FB_ACCEL_SAVAGE_MX_MV
	FB_ACCEL_SAVAGE_MX           = C.FB_ACCEL_SAVAGE_MX
	FB_ACCEL_SAVAGE_IX_MV        = C.FB_ACCEL_SAVAGE_IX_MV
	FB_ACCEL_SAVAGE_IX           = C.FB_ACCEL_SAVAGE_IX
	FB_ACCEL_PROSAVAGE_PM        = C.FB_ACCEL_PROSAVAGE_PM
	FB_ACCEL_PROSAVAGE_KM        = C.FB_ACCEL_PROSAVAGE_KM
	FB_ACCEL_S3TWISTER_P         = C.FB_ACCEL_S3TWISTER_P
	FB_ACCEL_S3TWISTER_K         = C.FB_ACCEL_S3TWISTER_K
	FB_ACCEL_SUPERSAVAGE         = C.FB_ACCEL_SUPERSAVAGE
	FB_ACCEL_PROSAVAGE_DDR       = C.FB_ACCEL_PROSAVAGE_DDR
	FB_ACCEL_PROSAVAGE_DDRK      = C.FB_ACCEL_PROSAVAGE_DDRK
	FB_ACCEL_PUV3_UNIGFX         = C.FB_ACCEL_PUV3_UNIGFX
	FB_CAP_FOURCC                = C.FB_CAP_FOURCC
	FB_NONSTD_HAM                = C.FB_NONSTD_HAM
	FB_NONSTD_REV_PIX_IN_B       = C.FB_NONSTD_REV_PIX_IN_B
	FB_ACTIVATE_NOW              = C.FB_ACTIVATE_NOW
	FB_ACTIVATE_NXTOPEN          = C.FB_ACTIVATE_NXTOPEN
	FB_ACTIVATE_TEST             = C.FB_ACTIVATE_TEST
	FB_ACTIVATE_MASK             = C.FB_ACTIVATE_MASK
	FB_ACTIVATE_VBL              = C.FB_ACTIVATE_VBL
	FB_CHANGE_CMAP_VBL           = C.FB_CHANGE_CMAP_VBL
	FB_ACTIVATE_ALL              = C.FB_ACTIVATE_ALL
	FB_ACTIVATE_FORCE            = C.FB_ACTIVATE_FORCE
	FB_ACTIVATE_INV_MODE         = C.FB_ACTIVATE_INV_MODE
	FB_ACCELF_TEXT               = C.FB_ACCELF_TEXT
	FB_SYNC_HOR_HIGH_ACT         = C.FB_SYNC_HOR_HIGH_ACT
	FB_SYNC_VERT_HIGH_ACT        = C.FB_SYNC_VERT_HIGH_ACT
	FB_SYNC_EXT                  = C.FB_SYNC_EXT
	FB_SYNC_COMP_HIGH_ACT        = C.FB_SYNC_COMP_HIGH_ACT
	FB_SYNC_BROADCAST            = C.FB_SYNC_BROADCAST
	FB_SYNC_ON_GREEN             = C.FB_SYNC_ON_GREEN
	FB_VMODE_NONINTERLACED       = C.FB_VMODE_NONINTERLACED
	FB_VMODE_INTERLACED          = C.FB_VMODE_INTERLACED
	FB_VMODE_DOUBLE              = C.FB_VMODE_DOUBLE
	FB_VMODE_ODD_FLD_FIRST       = C.FB_VMODE_ODD_FLD_FIRST
	FB_VMODE_MASK                = C.FB_VMODE_MASK
	FB_VMODE_YWRAP               = C.FB_VMODE_YWRAP
	FB_VMODE_SMOOTH_XPAN         = C.FB_VMODE_SMOOTH_XPAN
	FB_VMODE_CONUPDATE           = C.FB_VMODE_CONUPDATE
	FB_ROTATE_UR                 = C.FB_ROTATE_UR
	FB_ROTATE_CW                 = C.FB_ROTATE_CW
	FB_ROTATE_UD                 = C.FB_ROTATE_UD
	FB_ROTATE_CCW                = C.FB_ROTATE_CCW
	VESA_NO_BLANKING             = C.VESA_NO_BLANKING
	VESA_VSYNC_SUSPEND           = C.VESA_VSYNC_SUSPEND
	VESA_HSYNC_SUSPEND           = C.VESA_HSYNC_SUSPEND
	VESA_POWERDOWN               = C.VESA_POWERDOWN
	FB_VBLANK_VBLANKING          = C.FB_VBLANK_VBLANKING
	FB_VBLANK_HBLANKING          = C.FB_VBLANK_HBLANKING
	FB_VBLANK_HAVE_VBLANK        = C.FB_VBLANK_HAVE_VBLANK
	FB_VBLANK_HAVE_HBLANK        = C.FB_VBLANK_HAVE_HBLANK
	FB_VBLANK_HAVE_COUNT         = C.FB_VBLANK_HAVE_COUNT
	FB_VBLANK_HAVE_VCOUNT        = C.FB_VBLANK_HAVE_VCOUNT
	FB_VBLANK_HAVE_HCOUNT        = C.FB_VBLANK_HAVE_HCOUNT
	FB_VBLANK_VSYNCING           = C.FB_VBLANK_VSYNCING
	FB_VBLANK_HAVE_VSYNC         = C.FB_VBLANK_HAVE_VSYNC
	ROP_COPY                     = C.ROP_COPY
	ROP_XOR                      = C.ROP_XOR
	FB_CUR_SETIMAGE              = C.FB_CUR_SETIMAGE
	FB_CUR_SETPOS                = C.FB_CUR_SETPOS
	FB_CUR_SETHOT                = C.FB_CUR_SETHOT
	FB_CUR_SETCMAP               = C.FB_CUR_SETCMAP
	FB_CUR_SETSHAPE              = C.FB_CUR_SETSHAPE
	FB_CUR_SETSIZE               = C.FB_CUR_SETSIZE
	FB_CUR_SETALL                = C.FB_CUR_SETALL
	FB_BACKLIGHT_LEVELS          = C.FB_BACKLIGHT_LEVELS
	FB_BACKLIGHT_MAX             = C.FB_BACKLIGHT_MAX
)
